name: state_machine
version: 2.0.5
description: Finite state machine library. Easily define legal state transitions. Listen to state entrances, departures, and transitions.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
homepage: https://github.com/Workiva/state_machine

environment:
  sdk: ^2.5.0

dependencies:
  w_common:

dev_dependencies:
  build_runner:
  build_test:
  build_web_compilers:
  coverage:
  dart_dev:
  dart_style:
  test:
